/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PendingBlock,
    PendingBlockFromJSON,
    PendingBlockFromJSONTyped,
    PendingBlockToJSON,
} from './';

/**
 * 
 * @export
 * @interface AccountsPendingResponse
 */
export interface AccountsPendingResponse {
    /**
     * 
     * @type {{ [key: string]: { [key: string]: PendingBlock; }; }}
     * @memberof AccountsPendingResponse
     */
    blocks?: { [key: string]: { [key: string]: PendingBlock; }; };
}

export function AccountsPendingResponseFromJSON(json: any): AccountsPendingResponse {
    return AccountsPendingResponseFromJSONTyped(json, false);
}

export function AccountsPendingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountsPendingResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blocks': !exists(json, 'blocks') ? undefined : json['blocks'],
    };
}

export function AccountsPendingResponseToJSON(value?: AccountsPendingResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blocks': value.blocks,
    };
}


