/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountsFrontiersRequest
 */
export interface AccountsFrontiersRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountsFrontiersRequest
     */
    action?: AccountsFrontiersRequestActionEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccountsFrontiersRequest
     */
    accounts?: Array<string>;
}

export function AccountsFrontiersRequestFromJSON(json: any): AccountsFrontiersRequest {
    return AccountsFrontiersRequestFromJSONTyped(json, false);
}

export function AccountsFrontiersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountsFrontiersRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': !exists(json, 'action') ? undefined : json['action'],
        'accounts': !exists(json, 'accounts') ? undefined : json['accounts'],
    };
}

export function AccountsFrontiersRequestToJSON(value?: AccountsFrontiersRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'accounts': value.accounts,
    };
}

/**
* @export
* @enum {string}
*/
export enum AccountsFrontiersRequestActionEnum {
    AccountsFrontiers = 'accounts_frontiers'
}


