/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountBalanceRequest
 */
export interface AccountBalanceRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountBalanceRequest
     */
    action: AccountBalanceRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof AccountBalanceRequest
     */
    account: string;
}

export function AccountBalanceRequestFromJSON(json: any): AccountBalanceRequest {
    return AccountBalanceRequestFromJSONTyped(json, false);
}

export function AccountBalanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountBalanceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'account': json['account'],
    };
}

export function AccountBalanceRequestToJSON(value?: AccountBalanceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'account': value.account,
    };
}

/**
* @export
* @enum {string}
*/
export enum AccountBalanceRequestActionEnum {
    AccountBalance = 'account_balance'
}


