/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountWeightRequest
 */
export interface AccountWeightRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountWeightRequest
     */
    action?: AccountWeightRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof AccountWeightRequest
     */
    account?: string;
}

export function AccountWeightRequestFromJSON(json: any): AccountWeightRequest {
    return AccountWeightRequestFromJSONTyped(json, false);
}

export function AccountWeightRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountWeightRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': !exists(json, 'action') ? undefined : json['action'],
        'account': !exists(json, 'account') ? undefined : json['account'],
    };
}

export function AccountWeightRequestToJSON(value?: AccountWeightRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'account': value.account,
    };
}

/**
* @export
* @enum {string}
*/
export enum AccountWeightRequestActionEnum {
    AccountWeight = 'account_weight'
}


