/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockHashResponse
 */
export interface BlockHashResponse {
    /**
     * 
     * @type {string}
     * @memberof BlockHashResponse
     */
    hash?: string;
}

export function BlockHashResponseFromJSON(json: any): BlockHashResponse {
    return BlockHashResponseFromJSONTyped(json, false);
}

export function BlockHashResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockHashResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
    };
}

export function BlockHashResponseToJSON(value?: BlockHashResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hash': value.hash,
    };
}


