/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockAccountResponse
 */
export interface BlockAccountResponse {
    /**
     * 
     * @type {string}
     * @memberof BlockAccountResponse
     */
    account?: string;
}

export function BlockAccountResponseFromJSON(json: any): BlockAccountResponse {
    return BlockAccountResponseFromJSONTyped(json, false);
}

export function BlockAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockAccountResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'account': !exists(json, 'account') ? undefined : json['account'],
    };
}

export function BlockAccountResponseToJSON(value?: BlockAccountResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account': value.account,
    };
}


