/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockCountTypeResponse
 */
export interface BlockCountTypeResponse {
    /**
     * 
     * @type {string}
     * @memberof BlockCountTypeResponse
     */
    send: string;
    /**
     * 
     * @type {string}
     * @memberof BlockCountTypeResponse
     */
    receive: string;
    /**
     * 
     * @type {string}
     * @memberof BlockCountTypeResponse
     */
    open: string;
    /**
     * 
     * @type {string}
     * @memberof BlockCountTypeResponse
     */
    change: string;
    /**
     * 
     * @type {string}
     * @memberof BlockCountTypeResponse
     */
    stateV0: string;
    /**
     * 
     * @type {string}
     * @memberof BlockCountTypeResponse
     */
    stateV1: string;
    /**
     * 
     * @type {string}
     * @memberof BlockCountTypeResponse
     */
    state: string;
}

export function BlockCountTypeResponseFromJSON(json: any): BlockCountTypeResponse {
    return BlockCountTypeResponseFromJSONTyped(json, false);
}

export function BlockCountTypeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockCountTypeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'send': json['send'],
        'receive': json['receive'],
        'open': json['open'],
        'change': json['change'],
        'stateV0': json['state_v0'],
        'stateV1': json['state_v1'],
        'state': json['state'],
    };
}

export function BlockCountTypeResponseToJSON(value?: BlockCountTypeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'send': value.send,
        'receive': value.receive,
        'open': value.open,
        'change': value.change,
        'state_v0': value.stateV0,
        'state_v1': value.stateV1,
        'state': value.state,
    };
}


