/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BootstrapAnyRequest
 */
export interface BootstrapAnyRequest {
    /**
     * 
     * @type {string}
     * @memberof BootstrapAnyRequest
     */
    action: BootstrapAnyRequestActionEnum;
}

export function BootstrapAnyRequestFromJSON(json: any): BootstrapAnyRequest {
    return BootstrapAnyRequestFromJSONTyped(json, false);
}

export function BootstrapAnyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BootstrapAnyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
    };
}

export function BootstrapAnyRequestToJSON(value?: BootstrapAnyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
    };
}

/**
* @export
* @enum {string}
*/
export enum BootstrapAnyRequestActionEnum {
    BootstrapAny = 'bootstrap_any'
}


