/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmationHistoryRequest
 */
export interface ConfirmationHistoryRequest {
    /**
     * 
     * @type {string}
     * @memberof ConfirmationHistoryRequest
     */
    action: ConfirmationHistoryRequestActionEnum;
}

export function ConfirmationHistoryRequestFromJSON(json: any): ConfirmationHistoryRequest {
    return ConfirmationHistoryRequestFromJSONTyped(json, false);
}

export function ConfirmationHistoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmationHistoryRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
    };
}

export function ConfirmationHistoryRequestToJSON(value?: ConfirmationHistoryRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
    };
}

/**
* @export
* @enum {string}
*/
export enum ConfirmationHistoryRequestActionEnum {
    ConfirmationHistory = 'confirmation_history'
}


