/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmationActiveRequest
 */
export interface ConfirmationActiveRequest {
    /**
     * 
     * @type {string}
     * @memberof ConfirmationActiveRequest
     */
    action: ConfirmationActiveRequestActionEnum;
    /**
     * Number, 0 by default. Returns only active elections with equal or higher announcements count. Useful to find long running elections
     * @type {string}
     * @memberof ConfirmationActiveRequest
     */
    announcements?: string;
}

export function ConfirmationActiveRequestFromJSON(json: any): ConfirmationActiveRequest {
    return ConfirmationActiveRequestFromJSONTyped(json, false);
}

export function ConfirmationActiveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmationActiveRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'announcements': !exists(json, 'announcements') ? undefined : json['announcements'],
    };
}

export function ConfirmationActiveRequestToJSON(value?: ConfirmationActiveRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'announcements': value.announcements,
    };
}

/**
* @export
* @enum {string}
*/
export enum ConfirmationActiveRequestActionEnum {
    ConfirmationActive = 'confirmation_active'
}


