/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Confirmation
 */
export interface Confirmation {
    /**
     * 
     * @type {string}
     * @memberof Confirmation
     */
    hash?: string;
    /**
     * Duration in milliseconds.
     * @type {string}
     * @memberof Confirmation
     */
    duration?: string;
    /**
     * 
     * @type {string}
     * @memberof Confirmation
     */
    time?: string;
    /**
     * 1 raw is the smallest possible division and NANO/Nano (Mnano) is the current standard division used in most wallets, on exchanges, etc.
     * @type {number}
     * @memberof Confirmation
     */
    tally?: number;
}

export function ConfirmationFromJSON(json: any): Confirmation {
    return ConfirmationFromJSONTyped(json, false);
}

export function ConfirmationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Confirmation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'time': !exists(json, 'time') ? undefined : json['time'],
        'tally': !exists(json, 'tally') ? undefined : json['tally'],
    };
}

export function ConfirmationToJSON(value?: Confirmation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hash': value.hash,
        'duration': value.duration,
        'time': value.time,
        'tally': value.tally,
    };
}


