/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeyExpandRequest
 */
export interface KeyExpandRequest {
    /**
     * 
     * @type {string}
     * @memberof KeyExpandRequest
     */
    action?: KeyExpandRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof KeyExpandRequest
     */
    key?: string;
}

export function KeyExpandRequestFromJSON(json: any): KeyExpandRequest {
    return KeyExpandRequestFromJSONTyped(json, false);
}

export function KeyExpandRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyExpandRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': !exists(json, 'action') ? undefined : json['action'],
        'key': !exists(json, 'key') ? undefined : json['key'],
    };
}

export function KeyExpandRequestToJSON(value?: KeyExpandRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'key': value.key,
    };
}

/**
* @export
* @enum {string}
*/
export enum KeyExpandRequestActionEnum {
    KeyExpand = 'key_expand'
}


