/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ModelBoolean {
    True = 'true',
    False = 'false'
}

export function ModelBooleanFromJSON(json: any): ModelBoolean {
    return ModelBooleanFromJSONTyped(json, false);
}

export function ModelBooleanFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelBoolean {
    return json as ModelBoolean;
}

export function ModelBooleanToJSON(value?: ModelBoolean | null): any {
    return value as any;
}

