/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * OpenAPI spec version: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelBoolean } from './ModelBoolean';
import { HttpFile } from '../http/http';

export class AccountInfoRequest {
    'action'?: AccountInfoRequestActionEnum;
    'account'?: string;
    /**
    * Boolean, false by default. Returns representative when set to true. 
    */
    'representative'?: ModelBoolean;
    /**
    * Boolean, false by default. Returns weigth when set to true. 
    */
    'weight'?: ModelBoolean;
    /**
    * Boolean, false by default. Returns pending when set to true. 
    */
    'pending'?: ModelBoolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "AccountInfoRequestActionEnum",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string",
            "format": ""
        },
        {
            "name": "representative",
            "baseName": "representative",
            "type": "ModelBoolean",
            "format": ""
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "ModelBoolean",
            "format": ""
        },
        {
            "name": "pending",
            "baseName": "pending",
            "type": "ModelBoolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountInfoRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type AccountInfoRequestActionEnum = "account_info" ;

