/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * OpenAPI spec version: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BlockDataJson } from './BlockDataJson';
import { ModelBoolean } from './ModelBoolean';
import { HttpFile } from '../http/http';

export class BlockHashRequest {
    'action': BlockHashRequestActionEnum;
    /**
    * Defaults to `\"false\"`. If `\"true\"`, `\"block\"` contains a JSON subtree instead of a JSON string.
    */
    'jsonBlock'?: ModelBoolean;
    'block': BlockDataJson;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "BlockHashRequestActionEnum",
            "format": ""
        },
        {
            "name": "jsonBlock",
            "baseName": "json_block",
            "type": "ModelBoolean",
            "format": ""
        },
        {
            "name": "block",
            "baseName": "block",
            "type": "BlockDataJson",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BlockHashRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type BlockHashRequestActionEnum = "block_info" ;

