/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * OpenAPI spec version: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelBoolean } from './ModelBoolean';
import { HttpFile } from '../http/http';

export class ChainRequest {
    'action': ChainRequestActionEnum;
    'block': string;
    'count': string;
    /**
    * _version 18.0+_  Number, 0 by default. Return the account chain block hashes offset by the specified number of blocks 
    */
    'offset'?: string;
    /**
    * _version 18.0+_  Boolean, false by default. Returns a list of block hashes in the account chain starting at block up to count (direction from open block up to frontier, from older blocks to newer). Equal to [successors](https://docs.nano.org/commands/rpc-protocol/#successors) 
    */
    'reverse'?: ModelBoolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "ChainRequestActionEnum",
            "format": ""
        },
        {
            "name": "block",
            "baseName": "block",
            "type": "string",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "string",
            "format": ""
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "string",
            "format": ""
        },
        {
            "name": "reverse",
            "baseName": "reverse",
            "type": "ModelBoolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChainRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type ChainRequestActionEnum = "chain" ;

