/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * OpenAPI spec version: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelBoolean } from './ModelBoolean';
import { HttpFile } from '../http/http';

export class ConfirmationInfoRequest {
    'action': ConfirmationInfoRequestActionEnum;
    /**
    * Defaults to `\"false\"`. If `\"true\"`, `\"contents\"` contains a JSON subtree instead of a JSON string.
    */
    'jsonBlock'?: ModelBoolean;
    /**
    * Defaults to `\"true\"`. If `\"false\"`, disables contents for each block.
    */
    'contents'?: ModelBoolean;
    /**
    * Defaults to `\"false\"`. If `\"true\"`, returns a list of votes representatives & its weights for each block.
    */
    'representatives'?: ModelBoolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "ConfirmationInfoRequestActionEnum",
            "format": ""
        },
        {
            "name": "jsonBlock",
            "baseName": "json_block",
            "type": "ModelBoolean",
            "format": ""
        },
        {
            "name": "contents",
            "baseName": "contents",
            "type": "ModelBoolean",
            "format": ""
        },
        {
            "name": "representatives",
            "baseName": "representatives",
            "type": "ModelBoolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConfirmationInfoRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type ConfirmationInfoRequestActionEnum = "confirmation_info" ;

