swagger: '2.0'
info:
  version: 0.2.0
  title: nano-rpc-api
schemes:
  - http
paths:
  /:
    post:
      summary: Returns how many RAW is owned and how many have not yet been received by account
      parameters:
        - in: body
          name: body
          required: true
          schema: 
            $ref: '#/definitions/AccountBalanceRequest'
      responses:
        200:
          description: Returns the balance and pending of the given account
          schema:
            $ref: '#/definitions/AccountBalanceResponse'

definitions:
  AccountBalanceRequest:
    type: object
    required: 
      - action
      - account
    properties:
      action:
        type: string
        enum: 
          - "account_balance"
      account: 
        $ref: '#/definitions/NanoAddress'
  NanoAddress:
    type: string
    example: "nano_1hzoje373eapce4ses7xsx539suww5555hi9q8i8j7hpbayzxq4c4nn91hr8"
  AccountBalanceResponse:
    type: object
    properties:
      balance:
        type: number
        example: '1000'
      pending: 
        type: number
        example: '1000'
      
