/*
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccountInfoResponse
 */
public class AccountInfoResponseTest {
    private final AccountInfoResponse model = new AccountInfoResponse();

    /**
     * Model tests for AccountInfoResponse
     */
    @Test
    public void testAccountInfoResponse() {
        // TODO: test AccountInfoResponse
    }

    /**
     * Test the property 'frontier'
     */
    @Test
    public void frontierTest() {
        // TODO: test frontier
    }

    /**
     * Test the property 'openBlock'
     */
    @Test
    public void openBlockTest() {
        // TODO: test openBlock
    }

    /**
     * Test the property 'representativeBlock'
     */
    @Test
    public void representativeBlockTest() {
        // TODO: test representativeBlock
    }

    /**
     * Test the property 'balance'
     */
    @Test
    public void balanceTest() {
        // TODO: test balance
    }

    /**
     * Test the property 'modifiedTimestamp'
     */
    @Test
    public void modifiedTimestampTest() {
        // TODO: test modifiedTimestamp
    }

    /**
     * Test the property 'blockCount'
     */
    @Test
    public void blockCountTest() {
        // TODO: test blockCount
    }

    /**
     * Test the property 'confirmationHeight'
     */
    @Test
    public void confirmationHeightTest() {
        // TODO: test confirmationHeight
    }

    /**
     * Test the property 'accountVersion'
     */
    @Test
    public void accountVersionTest() {
        // TODO: test accountVersion
    }

}
