/*
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Confirmation;
import org.openapitools.client.model.ConfirmationHistoryResponseConfirmationStats;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConfirmationHistoryResponse
 */
public class ConfirmationHistoryResponseTest {
    private final ConfirmationHistoryResponse model = new ConfirmationHistoryResponse();

    /**
     * Model tests for ConfirmationHistoryResponse
     */
    @Test
    public void testConfirmationHistoryResponse() {
        // TODO: test ConfirmationHistoryResponse
    }

    /**
     * Test the property 'confirmationStats'
     */
    @Test
    public void confirmationStatsTest() {
        // TODO: test confirmationStats
    }

    /**
     * Test the property 'confirmations'
     */
    @Test
    public void confirmationsTest() {
        // TODO: test confirmations
    }

}
