/*
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WorkGenerateResponse
 */
public class WorkGenerateResponseTest {
    private final WorkGenerateResponse model = new WorkGenerateResponse();

    /**
     * Model tests for WorkGenerateResponse
     */
    @Test
    public void testWorkGenerateResponse() {
        // TODO: test WorkGenerateResponse
    }

    /**
     * Test the property 'work'
     */
    @Test
    public void workTest() {
        // TODO: test work
    }

    /**
     * Test the property 'difficulty'
     */
    @Test
    public void difficultyTest() {
        // TODO: test difficulty
    }

    /**
     * Test the property 'multiplier'
     */
    @Test
    public void multiplierTest() {
        // TODO: test multiplier
    }

}
