/*
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.PendingBlock;

/**
 * AccountsPendingResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-08-17T13:51:05.488+02:00[Europe/Oslo]")
public class AccountsPendingResponse {
  public static final String SERIALIZED_NAME_BLOCKS = "blocks";
  @SerializedName(SERIALIZED_NAME_BLOCKS)
  private Map<String, Map> blocks = new HashMap<String, Map>();

  public AccountsPendingResponse blocks(Map<String, Map> blocks) {
    this.blocks = blocks;
    return this;
  }

  public AccountsPendingResponse putBlocksItem(String key, Map<String, PendingBlock> blocksItem) {
    if (this.blocks == null) {
      this.blocks = new HashMap<String, Map>();
    }
    this.blocks.put(key, blocksItem);
    return this;
  }

   /**
   * Get blocks
   * @return blocks
  **/
  @ApiModelProperty(example = "{\"nano_1111111111111111111111111111111111111111111111111117353trpda\":{\"142A538F36833D1CC78B94E11C766F75818F8B940771335C6C1B8AB880C5BB1D\":{\"amount\":\"6000000000000000000000000000000\",\"source\":\"nano_3dcfozsmekr1tr9skf1oa5wbgmxt81qepfdnt7zicq5x3hk65fg4fqj58mbr\"}}}", value = "")
  public Map<String, Map> getBlocks() {
    return blocks;
  }

  public void setBlocks(Map<String, Map> blocks) {
    this.blocks = blocks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountsPendingResponse accountsPendingResponse = (AccountsPendingResponse) o;
    return Objects.equals(this.blocks, accountsPendingResponse.blocks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blocks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountsPendingResponse {\n");
    sb.append("    blocks: ").append(toIndentedString(blocks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

