/*
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.ConfirmationInfo;

/**
 * ConfirmationInfoResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-07T20:00:02.801+01:00[Europe/Oslo]")
public class ConfirmationInfoResponse {
  public static final String SERIALIZED_NAME_ANNOUNCEMENTS = "announcements";
  @SerializedName(SERIALIZED_NAME_ANNOUNCEMENTS)
  private String announcements;

  public static final String SERIALIZED_NAME_LAST_WINNER = "last_winner";
  @SerializedName(SERIALIZED_NAME_LAST_WINNER)
  private String lastWinner;

  public static final String SERIALIZED_NAME_TOTAL_TALLY = "total_tally";
  @SerializedName(SERIALIZED_NAME_TOTAL_TALLY)
  private BigDecimal totalTally;

  public static final String SERIALIZED_NAME_BLOCKS = "blocks";
  @SerializedName(SERIALIZED_NAME_BLOCKS)
  private Map<String, ConfirmationInfo> blocks = null;


  public ConfirmationInfoResponse announcements(String announcements) {
    
    this.announcements = announcements;
    return this;
  }

   /**
   * Get announcements
   * @return announcements
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2", value = "")

  public String getAnnouncements() {
    return announcements;
  }


  public void setAnnouncements(String announcements) {
    this.announcements = announcements;
  }


  public ConfirmationInfoResponse lastWinner(String lastWinner) {
    
    this.lastWinner = lastWinner;
    return this;
  }

   /**
   * Get lastWinner
   * @return lastWinner
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "8D3AB98B301224253750D448B4BD997132400CEDD0A8432F775724F2D9821C72", value = "")

  public String getLastWinner() {
    return lastWinner;
  }


  public void setLastWinner(String lastWinner) {
    this.lastWinner = lastWinner;
  }


  public ConfirmationInfoResponse totalTally(BigDecimal totalTally) {
    
    this.totalTally = totalTally;
    return this;
  }

   /**
   * 1 raw is the smallest possible division and NANO/Nano (Mnano) is the current standard division used in most wallets, on exchanges, etc.
   * @return totalTally
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1000000000000000000000000000000", value = "1 raw is the smallest possible division and NANO/Nano (Mnano) is the current standard division used in most wallets, on exchanges, etc.")

  public BigDecimal getTotalTally() {
    return totalTally;
  }


  public void setTotalTally(BigDecimal totalTally) {
    this.totalTally = totalTally;
  }


  public ConfirmationInfoResponse blocks(Map<String, ConfirmationInfo> blocks) {
    
    this.blocks = blocks;
    return this;
  }

  public ConfirmationInfoResponse putBlocksItem(String key, ConfirmationInfo blocksItem) {
    if (this.blocks == null) {
      this.blocks = new HashMap<String, ConfirmationInfo>();
    }
    this.blocks.put(key, blocksItem);
    return this;
  }

   /**
   * Get blocks
   * @return blocks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"B94C505029F04BC057A0486ADA8BD07981B4A8736AE6581F2E98C6D18498146F\":{\"tally\":\"51145880360832646375807054724596663794\",\"contents\":{\"type\":\"state\",\"account\":\"nano_3fihmbtuod33s4nrbqfczhk9zy9ddqimwjshzg4c3857es8c9631i5rg6h9p\",\"previous\":\"EE125B1B1D85D3C24636B3590E1642D9F21B166C0C6CD99C9C6087A1224A0C44\",\"representative\":\"nano_3o7uzba8b9e1wqu5ziwpruteyrs3scyqr761x7ke6w1xctohxfh5du75qgaj\",\"balance\":\"218195000000000000000000000000\",\"link\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"link_as_account\":\"nano_1111111111111111111111111111111111111111111111111111hifc8npp\",\"signature\":\"B1BD285235C612C5A141FA61793D7C6C762D3F104A85102DED5FBD6B4514971C4D044ACD3EC8C06A9495D8E83B6941B54F8DABA825ADF799412ED9E2C86D7A0C\",\"work\":\"05bb28cd8acbe71d\"}}}", value = "")

  public Map<String, ConfirmationInfo> getBlocks() {
    return blocks;
  }


  public void setBlocks(Map<String, ConfirmationInfo> blocks) {
    this.blocks = blocks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfirmationInfoResponse confirmationInfoResponse = (ConfirmationInfoResponse) o;
    return Objects.equals(this.announcements, confirmationInfoResponse.announcements) &&
        Objects.equals(this.lastWinner, confirmationInfoResponse.lastWinner) &&
        Objects.equals(this.totalTally, confirmationInfoResponse.totalTally) &&
        Objects.equals(this.blocks, confirmationInfoResponse.blocks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(announcements, lastWinner, totalTally, blocks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfirmationInfoResponse {\n");
    sb.append("    announcements: ").append(toIndentedString(announcements)).append("\n");
    sb.append("    lastWinner: ").append(toIndentedString(lastWinner)).append("\n");
    sb.append("    totalTally: ").append(toIndentedString(totalTally)).append("\n");
    sb.append("    blocks: ").append(toIndentedString(blocks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

