/*
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets SubType
 */
@JsonAdapter(SubType.Adapter.class)
public enum SubType {
  
  SEND("send");

  private String value;

  SubType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SubType fromValue(String value) {
    for (SubType b : SubType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<SubType> {
    @Override
    public void write(final JsonWriter jsonWriter, final SubType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SubType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SubType.fromValue(value);
    }
  }
}

