/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ConfirmationHeightCurrentlyProcessingRequest,
    ConfirmationHeightCurrentlyProcessingRequestFromJSON,
    ConfirmationHeightCurrentlyProcessingRequestToJSON,
    ConfirmationHeightCurrentlyProcessingResponse,
    ConfirmationHeightCurrentlyProcessingResponseFromJSON,
    ConfirmationHeightCurrentlyProcessingResponseToJSON,
} from '../models';

export interface ConfirmationHeightCurrentlyProcessingOperationRequest {
    confirmationHeightCurrentlyProcessingRequest?: ConfirmationHeightCurrentlyProcessingRequest;
}

/**
 * 
 */
export class DebugApi extends runtime.BaseAPI {

    /**
     * _version 19.0+_  Returns the hash of the block which is having the confirmation height set for, error otherwise. When a block is being confirmed, it must confirm all blocks in the chain below and iteratively follow all receive blocks. This can take a long time, so it can be useful to find which block was the original being confirmed. 
     */
    async confirmationHeightCurrentlyProcessingRaw(requestParameters: ConfirmationHeightCurrentlyProcessingOperationRequest): Promise<runtime.ApiResponse<ConfirmationHeightCurrentlyProcessingResponse>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/#confirmation_height_currently_processing`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmationHeightCurrentlyProcessingRequestToJSON(requestParameters.confirmationHeightCurrentlyProcessingRequest),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfirmationHeightCurrentlyProcessingResponseFromJSON(jsonValue));
    }

    /**
     * _version 19.0+_  Returns the hash of the block which is having the confirmation height set for, error otherwise. When a block is being confirmed, it must confirm all blocks in the chain below and iteratively follow all receive blocks. This can take a long time, so it can be useful to find which block was the original being confirmed. 
     */
    async confirmationHeightCurrentlyProcessing(requestParameters: ConfirmationHeightCurrentlyProcessingOperationRequest): Promise<ConfirmationHeightCurrentlyProcessingResponse> {
        const response = await this.confirmationHeightCurrentlyProcessingRaw(requestParameters);
        return await response.value();
    }

}
