name: Production Build
on:
  push:
    tags:
      - "v*.*.*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Install modules
        run: npm --prefix clients/typescript-fetch/ install

      - name: Build
        run: npm --prefix clients/typescript-fetch/ run build

      - name: Upload Release Asset
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./clients/typescript-fetch/package.json
