/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountWeightResponse
 */
export interface AccountWeightResponse {
    /**
     * 1 raw is the smallest possible division and NANO/Nano (Mnano) is the current standard division used in most wallets, on exchanges, etc.
     * @type {number}
     * @memberof AccountWeightResponse
     */
    weight?: number;
}

export function AccountWeightResponseFromJSON(json: any): AccountWeightResponse {
    return AccountWeightResponseFromJSONTyped(json, false);
}

export function AccountWeightResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountWeightResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'weight': !exists(json, 'weight') ? undefined : json['weight'],
    };
}

export function AccountWeightResponseToJSON(value?: AccountWeightResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'weight': value.weight,
    };
}


