// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountGetResponse
 */
export interface AccountGetResponse {
    /**
     * 
     * @type {string}
     * @memberof AccountGetResponse
     */
    account?: string;
}

export function AccountGetResponseFromJSON(json: any): AccountGetResponse {
    return {
        'account': !exists(json, 'account') ? undefined : json['account'],
    };
}

export function AccountGetResponseToJSON(value?: AccountGetResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'account': value.account,
    };
}


