// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountsFrontiersResponse
 */
export interface AccountsFrontiersResponse {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof AccountsFrontiersResponse
     */
    frontiers?: { [key: string]: string; };
}

export function AccountsFrontiersResponseFromJSON(json: any): AccountsFrontiersResponse {
    return {
        'frontiers': !exists(json, 'frontiers') ? undefined : json['frontiers'],
    };
}

export function AccountsFrontiersResponseToJSON(value?: AccountsFrontiersResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'frontiers': value.frontiers,
    };
}


