/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountHistoryRequest
 */
export interface AccountHistoryRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountHistoryRequest
     */
    action: AccountHistoryRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof AccountHistoryRequest
     */
    account?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountHistoryRequest
     */
    count?: string;
}

export function AccountHistoryRequestFromJSON(json: any): AccountHistoryRequest {
    return AccountHistoryRequestFromJSONTyped(json, false);
}

export function AccountHistoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountHistoryRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'account': !exists(json, 'account') ? undefined : json['account'],
        'count': !exists(json, 'count') ? undefined : json['count'],
    };
}

export function AccountHistoryRequestToJSON(value?: AccountHistoryRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'account': value.account,
        'count': value.count,
    };
}

/**
* @export
* @enum {string}
*/
export enum AccountHistoryRequestActionEnum {
    AccountHistory = 'account_history'
}


