// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccountBalanceResponse,
    AccountBalanceResponseFromJSON,
    AccountBalanceResponseToJSON,
} from './';

/**
 * 
 * @export
 * @interface AccountsBalancesResponse
 */
export interface AccountsBalancesResponse {
    /**
     * 
     * @type {{ [key: string]: AccountBalanceResponse; }}
     * @memberof AccountsBalancesResponse
     */
    balances?: { [key: string]: AccountBalanceResponse; };
}

export function AccountsBalancesResponseFromJSON(json: any): AccountsBalancesResponse {
    return {
        'balances': !exists(json, 'balances') ? undefined : mapValues(json['balances'], AccountBalanceResponseFromJSON),
    };
}

export function AccountsBalancesResponseToJSON(value?: AccountsBalancesResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'balances': value.balances === undefined ? undefined : mapValues(value.balances, AccountBalanceResponseToJSON),
    };
}


