// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountRepresentativeResponse
 */
export interface AccountRepresentativeResponse {
    /**
     * 
     * @type {string}
     * @memberof AccountRepresentativeResponse
     */
    representative?: string;
}

export function AccountRepresentativeResponseFromJSON(json: any): AccountRepresentativeResponse {
    return {
        'representative': !exists(json, 'representative') ? undefined : json['representative'],
    };
}

export function AccountRepresentativeResponseToJSON(value?: AccountRepresentativeResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'representative': value.representative,
    };
}


