/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountKeyResponse
 */
export interface AccountKeyResponse {
    /**
     * 
     * @type {string}
     * @memberof AccountKeyResponse
     */
    key?: string;
}

export function AccountKeyResponseFromJSON(json: any): AccountKeyResponse {
    return AccountKeyResponseFromJSONTyped(json, false);
}

export function AccountKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountKeyResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
    };
}

export function AccountKeyResponseToJSON(value?: AccountKeyResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
    };
}


