// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountBlockCountRequest
 */
export interface AccountBlockCountRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountBlockCountRequest
     */
    action: AccountBlockCountRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof AccountBlockCountRequest
     */
    account: string;
}

export function AccountBlockCountRequestFromJSON(json: any): AccountBlockCountRequest {
    return {
        'action': json['action'],
        'account': json['account'],
    };
}

export function AccountBlockCountRequestToJSON(value?: AccountBlockCountRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'action': value.action,
        'account': value.account,
    };
}

/**
* @export
* @enum {string}
*/
export enum AccountBlockCountRequestActionEnum {
    AccountBlockCount = 'account_block_count'
}


