// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountsBalancesRequest
 */
export interface AccountsBalancesRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountsBalancesRequest
     */
    action?: AccountsBalancesRequestActionEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccountsBalancesRequest
     */
    accounts?: Array<string>;
}

export function AccountsBalancesRequestFromJSON(json: any): AccountsBalancesRequest {
    return {
        'action': !exists(json, 'action') ? undefined : json['action'],
        'accounts': !exists(json, 'accounts') ? undefined : json['accounts'],
    };
}

export function AccountsBalancesRequestToJSON(value?: AccountsBalancesRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'action': value.action,
        'accounts': value.accounts,
    };
}

/**
* @export
* @enum {string}
*/
export enum AccountsBalancesRequestActionEnum {
    AccountsBalances = 'accounts_balances'
}


