// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PendingBlock,
    PendingBlockFromJSON,
    PendingBlockToJSON,
} from './';

/**
 * 
 * @export
 * @interface AccountsPendingResponse
 */
export interface AccountsPendingResponse {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AccountsPendingResponse
     */
    blocks?: { [key: string]: any; };
}

export function AccountsPendingResponseFromJSON(json: any): AccountsPendingResponse {
    return {
        'blocks': !exists(json, 'blocks') ? undefined : json['blocks'],
    };
}

export function AccountsPendingResponseToJSON(value?: AccountsPendingResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'blocks': value.blocks,
    };
}


