/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountInfoRequest
 */
export interface AccountInfoRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountInfoRequest
     */
    action?: AccountInfoRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof AccountInfoRequest
     */
    account?: string;
}

export function AccountInfoRequestFromJSON(json: any): AccountInfoRequest {
    return AccountInfoRequestFromJSONTyped(json, false);
}

export function AccountInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountInfoRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': !exists(json, 'action') ? undefined : json['action'],
        'account': !exists(json, 'account') ? undefined : json['account'],
    };
}

export function AccountInfoRequestToJSON(value?: AccountInfoRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'account': value.account,
    };
}

/**
* @export
* @enum {string}
*/
export enum AccountInfoRequestActionEnum {
    AccountInfo = 'account_info'
}


