// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountsCreateRequest
 */
export interface AccountsCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountsCreateRequest
     */
    action?: AccountsCreateRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof AccountsCreateRequest
     */
    wallet?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountsCreateRequest
     */
    count?: string;
}

export function AccountsCreateRequestFromJSON(json: any): AccountsCreateRequest {
    return {
        'action': !exists(json, 'action') ? undefined : json['action'],
        'wallet': !exists(json, 'wallet') ? undefined : json['wallet'],
        'count': !exists(json, 'count') ? undefined : json['count'],
    };
}

export function AccountsCreateRequestToJSON(value?: AccountsCreateRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'action': value.action,
        'wallet': value.wallet,
        'count': value.count,
    };
}

/**
* @export
* @enum {string}
*/
export enum AccountsCreateRequestActionEnum {
    AccountsCreate = 'accounts_create'
}


