/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Block,
    BlockFromJSON,
    BlockFromJSONTyped,
    BlockToJSON,
} from './';

/**
 * 
 * @export
 * @interface AccountHistoryResponse
 */
export interface AccountHistoryResponse {
    /**
     * 
     * @type {string}
     * @memberof AccountHistoryResponse
     */
    account?: string;
    /**
     * 
     * @type {Array<Block>}
     * @memberof AccountHistoryResponse
     */
    history?: Array<Block>;
    /**
     * 
     * @type {string}
     * @memberof AccountHistoryResponse
     */
    previous?: string;
}

export function AccountHistoryResponseFromJSON(json: any): AccountHistoryResponse {
    return AccountHistoryResponseFromJSONTyped(json, false);
}

export function AccountHistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountHistoryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'account': !exists(json, 'account') ? undefined : json['account'],
        'history': !exists(json, 'history') ? undefined : ((json['history'] as Array<any>).map(BlockFromJSON)),
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
    };
}

export function AccountHistoryResponseToJSON(value?: AccountHistoryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account': value.account,
        'history': value.history === undefined ? undefined : ((value.history as Array<any>).map(BlockToJSON)),
        'previous': value.previous,
    };
}


