// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActiveDifficultyRequest
 */
export interface ActiveDifficultyRequest {
    /**
     * 
     * @type {string}
     * @memberof ActiveDifficultyRequest
     */
    action: ActiveDifficultyRequestActionEnum;
    /**
     * Boolean, false by default. Also returns the trend of difficulty seen on the network as a list of multipliers. Sampling occurs every 16 to 36 seconds. The list is ordered such that the first value is the most recent sample. 
     * @type {boolean}
     * @memberof ActiveDifficultyRequest
     */
    includeTrend?: boolean;
}

export function ActiveDifficultyRequestFromJSON(json: any): ActiveDifficultyRequest {
    return {
        'action': json['action'],
        'includeTrend': !exists(json, 'include_trend') ? undefined : json['include_trend'],
    };
}

export function ActiveDifficultyRequestToJSON(value?: ActiveDifficultyRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'action': value.action,
        'include_trend': value.includeTrend,
    };
}

/**
* @export
* @enum {string}
*/
export enum ActiveDifficultyRequestActionEnum {
    ActiveDifficulty = 'active_difficulty'
}


