// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActiveDifficultyResponse
 */
export interface ActiveDifficultyResponse {
    /**
     * 
     * @type {string}
     * @memberof ActiveDifficultyResponse
     */
    networkMinimum?: string;
    /**
     * 
     * @type {string}
     * @memberof ActiveDifficultyResponse
     */
    networkCurrent?: string;
    /**
     * 
     * @type {string}
     * @memberof ActiveDifficultyResponse
     */
    multiplier?: string;
}

export function ActiveDifficultyResponseFromJSON(json: any): ActiveDifficultyResponse {
    return {
        'networkMinimum': !exists(json, 'network_minimum') ? undefined : json['network_minimum'],
        'networkCurrent': !exists(json, 'network_current') ? undefined : json['network_current'],
        'multiplier': !exists(json, 'multiplier') ? undefined : json['multiplier'],
    };
}

export function ActiveDifficultyResponseToJSON(value?: ActiveDifficultyResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'network_minimum': value.networkMinimum,
        'network_current': value.networkCurrent,
        'multiplier': value.multiplier,
    };
}


