// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AvailableSupplyRequest
 */
export interface AvailableSupplyRequest {
    /**
     * 
     * @type {string}
     * @memberof AvailableSupplyRequest
     */
    action: AvailableSupplyRequestActionEnum;
}

export function AvailableSupplyRequestFromJSON(json: any): AvailableSupplyRequest {
    return {
        'action': json['action'],
    };
}

export function AvailableSupplyRequestToJSON(value?: AvailableSupplyRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'action': value.action,
    };
}

/**
* @export
* @enum {string}
*/
export enum AvailableSupplyRequestActionEnum {
    AvailableSupply = 'available_supply'
}


