// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AvailableSupplyResponse
 */
export interface AvailableSupplyResponse {
    /**
     * 1 raw is the smallest possible division and NANO/Nano (Mnano) is the current standard division used in most wallets, on exchanges, etc.
     * @type {number}
     * @memberof AvailableSupplyResponse
     */
    available?: number;
}

export function AvailableSupplyResponseFromJSON(json: any): AvailableSupplyResponse {
    return {
        'available': !exists(json, 'available') ? undefined : json['available'],
    };
}

export function AvailableSupplyResponseToJSON(value?: AvailableSupplyResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'available': value.available,
    };
}


