/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlocksRequest
 */
export interface BlocksRequest {
    /**
     * 
     * @type {string}
     * @memberof BlocksRequest
     */
    action: BlocksRequestActionEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof BlocksRequest
     */
    hashes?: Array<string>;
}

export function BlocksRequestFromJSON(json: any): BlocksRequest {
    return BlocksRequestFromJSONTyped(json, false);
}

export function BlocksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlocksRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'hashes': !exists(json, 'hashes') ? undefined : json['hashes'],
    };
}

export function BlocksRequestToJSON(value?: BlocksRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'hashes': value.hashes,
    };
}

/**
* @export
* @enum {string}
*/
export enum BlocksRequestActionEnum {
    Blocks = 'blocks'
}


