// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockAccountResponse
 */
export interface BlockAccountResponse {
    /**
     * 
     * @type {string}
     * @memberof BlockAccountResponse
     */
    account?: string;
}

export function BlockAccountResponseFromJSON(json: any): BlockAccountResponse {
    return {
        'account': !exists(json, 'account') ? undefined : json['account'],
    };
}

export function BlockAccountResponseToJSON(value?: BlockAccountResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'account': value.account,
    };
}


