// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BlockInfo,
    BlockInfoFromJSON,
    BlockInfoToJSON,
} from './';

/**
 * 
 * @export
 * @interface BlocksInfoResponse
 */
export interface BlocksInfoResponse {
    /**
     * 
     * @type {{ [key: string]: BlockInfo; }}
     * @memberof BlocksInfoResponse
     */
    blocks?: { [key: string]: BlockInfo; };
}

export function BlocksInfoResponseFromJSON(json: any): BlocksInfoResponse {
    return {
        'blocks': !exists(json, 'blocks') ? undefined : mapValues(json['blocks'], BlockInfoFromJSON),
    };
}

export function BlocksInfoResponseToJSON(value?: BlocksInfoResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'blocks': value.blocks === undefined ? undefined : mapValues(value.blocks, BlockInfoToJSON),
    };
}


