// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlocksResponse
 */
export interface BlocksResponse {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof BlocksResponse
     */
    blocks?: { [key: string]: string; };
}

export function BlocksResponseFromJSON(json: any): BlocksResponse {
    return {
        'blocks': !exists(json, 'blocks') ? undefined : json['blocks'],
    };
}

export function BlocksResponseToJSON(value?: BlocksResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'blocks': value.blocks,
    };
}


