// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockCreateResponse
 */
export interface BlockCreateResponse {
    /**
     * 
     * @type {string}
     * @memberof BlockCreateResponse
     */
    hash?: string;
    /**
     * 
     * @type {string}
     * @memberof BlockCreateResponse
     */
    block?: string;
}

export function BlockCreateResponseFromJSON(json: any): BlockCreateResponse {
    return {
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
        'block': !exists(json, 'block') ? undefined : json['block'],
    };
}

export function BlockCreateResponseToJSON(value?: BlockCreateResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'hash': value.hash,
        'block': value.block,
    };
}


