/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockAccountRequest
 */
export interface BlockAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof BlockAccountRequest
     */
    action: BlockAccountRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof BlockAccountRequest
     */
    hash?: string;
}

export function BlockAccountRequestFromJSON(json: any): BlockAccountRequest {
    return BlockAccountRequestFromJSONTyped(json, false);
}

export function BlockAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockAccountRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
    };
}

export function BlockAccountRequestToJSON(value?: BlockAccountRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'hash': value.hash,
    };
}

/**
* @export
* @enum {string}
*/
export enum BlockAccountRequestActionEnum {
    BlockAccount = 'block_account'
}


