/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ModelBoolean,
    ModelBooleanFromJSON,
    ModelBooleanFromJSONTyped,
    ModelBooleanToJSON,
} from './';

/**
 * 
 * @export
 * @interface BootstrapLazyRequest
 */
export interface BootstrapLazyRequest {
    /**
     * 
     * @type {string}
     * @memberof BootstrapLazyRequest
     */
    action: BootstrapLazyRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof BootstrapLazyRequest
     */
    hash: string;
    /**
     * Boolean, false by default. Manually force closing of all current bootstraps.
     * @type {ModelBoolean}
     * @memberof BootstrapLazyRequest
     */
    force?: ModelBoolean;
}

export function BootstrapLazyRequestFromJSON(json: any): BootstrapLazyRequest {
    return BootstrapLazyRequestFromJSONTyped(json, false);
}

export function BootstrapLazyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BootstrapLazyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'hash': json['hash'],
        'force': !exists(json, 'force') ? undefined : ModelBooleanFromJSON(json['force']),
    };
}

export function BootstrapLazyRequestToJSON(value?: BootstrapLazyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'hash': value.hash,
        'force': ModelBooleanToJSON(value.force),
    };
}

/**
* @export
* @enum {string}
*/
export enum BootstrapLazyRequestActionEnum {
    BootstrapAny = 'bootstrap_any'
}


