/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmationActiveResponse
 */
export interface ConfirmationActiveResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfirmationActiveResponse
     */
    confirmations?: Array<string>;
}

export function ConfirmationActiveResponseFromJSON(json: any): ConfirmationActiveResponse {
    return ConfirmationActiveResponseFromJSONTyped(json, false);
}

export function ConfirmationActiveResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmationActiveResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'confirmations': !exists(json, 'confirmations') ? undefined : json['confirmations'],
    };
}

export function ConfirmationActiveResponseToJSON(value?: ConfirmationActiveResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'confirmations': value.confirmations,
    };
}


