/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmationHeightCurrentlyProcessingRequest
 */
export interface ConfirmationHeightCurrentlyProcessingRequest {
    /**
     * 
     * @type {string}
     * @memberof ConfirmationHeightCurrentlyProcessingRequest
     */
    action: ConfirmationHeightCurrentlyProcessingRequestActionEnum;
}

export function ConfirmationHeightCurrentlyProcessingRequestFromJSON(json: any): ConfirmationHeightCurrentlyProcessingRequest {
    return ConfirmationHeightCurrentlyProcessingRequestFromJSONTyped(json, false);
}

export function ConfirmationHeightCurrentlyProcessingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmationHeightCurrentlyProcessingRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
    };
}

export function ConfirmationHeightCurrentlyProcessingRequestToJSON(value?: ConfirmationHeightCurrentlyProcessingRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
    };
}

/**
* @export
* @enum {string}
*/
export enum ConfirmationHeightCurrentlyProcessingRequestActionEnum {
    ConfirmationHeightCurrentlyProcessing = 'confirmation_height_currently_processing'
}


