// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeyCreateRequest
 */
export interface KeyCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof KeyCreateRequest
     */
    action?: KeyCreateRequestActionEnum;
}

export function KeyCreateRequestFromJSON(json: any): KeyCreateRequest {
    return {
        'action': !exists(json, 'action') ? undefined : json['action'],
    };
}

export function KeyCreateRequestToJSON(value?: KeyCreateRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'action': value.action,
    };
}

/**
* @export
* @enum {string}
*/
export enum KeyCreateRequestActionEnum {
    KeyCreate = 'key_create'
}


