/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PendingResponse
 */
export interface PendingResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof PendingResponse
     */
    blocks?: Array<string>;
}

export function PendingResponseFromJSON(json: any): PendingResponse {
    return PendingResponseFromJSONTyped(json, false);
}

export function PendingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PendingResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blocks': !exists(json, 'blocks') ? undefined : json['blocks'],
    };
}

export function PendingResponseToJSON(value?: PendingResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blocks': value.blocks,
    };
}


