/* tslint:disable */
/* eslint-disable */
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BlockDataJson,
    BlockDataJsonFromJSON,
    BlockDataJsonFromJSONTyped,
    BlockDataJsonToJSON,
    ModelBoolean,
    ModelBooleanFromJSON,
    ModelBooleanFromJSONTyped,
    ModelBooleanToJSON,
    SubType,
    SubTypeFromJSON,
    SubTypeFromJSONTyped,
    SubTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProcessRequest
 */
export interface ProcessRequest {
    /**
     * 
     * @type {string}
     * @memberof ProcessRequest
     */
    action: ProcessRequestActionEnum;
    /**
     * Defaults to `"false"`. If `"true"`, `"block"` contains a JSON subtree instead of a JSON string.
     * @type {ModelBoolean}
     * @memberof ProcessRequest
     */
    jsonBlock?: ModelBoolean;
    /**
     * 
     * @type {BlockDataJson}
     * @memberof ProcessRequest
     */
    block: BlockDataJson;
    /**
     * 
     * @type {SubType}
     * @memberof ProcessRequest
     */
    subtype?: SubType;
}

export function ProcessRequestFromJSON(json: any): ProcessRequest {
    return ProcessRequestFromJSONTyped(json, false);
}

export function ProcessRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'jsonBlock': !exists(json, 'json_block') ? undefined : ModelBooleanFromJSON(json['json_block']),
        'block': BlockDataJsonFromJSON(json['block']),
        'subtype': !exists(json, 'subtype') ? undefined : SubTypeFromJSON(json['subtype']),
    };
}

export function ProcessRequestToJSON(value?: ProcessRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'json_block': ModelBooleanToJSON(value.jsonBlock),
        'block': BlockDataJsonToJSON(value.block),
        'subtype': SubTypeToJSON(value.subtype),
    };
}

/**
* @export
* @enum {string}
*/
export enum ProcessRequestActionEnum {
    Process = 'process'
}


