// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcessRequest
 */
export interface ProcessRequest {
    /**
     * 
     * @type {string}
     * @memberof ProcessRequest
     */
    action?: ProcessRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof ProcessRequest
     */
    block?: string;
}

export function ProcessRequestFromJSON(json: any): ProcessRequest {
    return {
        'action': !exists(json, 'action') ? undefined : json['action'],
        'block': !exists(json, 'block') ? undefined : json['block'],
    };
}

export function ProcessRequestToJSON(value?: ProcessRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'action': value.action,
        'block': value.block,
    };
}

/**
* @export
* @enum {string}
*/
export enum ProcessRequestActionEnum {
    Process = 'process'
}


