// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReceiveRequest
 */
export interface ReceiveRequest {
    /**
     * 
     * @type {string}
     * @memberof ReceiveRequest
     */
    action?: ReceiveRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof ReceiveRequest
     */
    wallet?: string;
    /**
     * 
     * @type {string}
     * @memberof ReceiveRequest
     */
    account?: string;
    /**
     * 
     * @type {string}
     * @memberof ReceiveRequest
     */
    block?: string;
}

export function ReceiveRequestFromJSON(json: any): ReceiveRequest {
    return {
        'action': !exists(json, 'action') ? undefined : json['action'],
        'wallet': !exists(json, 'wallet') ? undefined : json['wallet'],
        'account': !exists(json, 'account') ? undefined : json['account'],
        'block': !exists(json, 'block') ? undefined : json['block'],
    };
}

export function ReceiveRequestToJSON(value?: ReceiveRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'action': value.action,
        'wallet': value.wallet,
        'account': value.account,
        'block': value.block,
    };
}

/**
* @export
* @enum {string}
*/
export enum ReceiveRequestActionEnum {
    Receive = 'receive'
}


