// tslint:disable
/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletCreateRequest
 */
export interface WalletCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof WalletCreateRequest
     */
    action?: WalletCreateRequestActionEnum;
}

export function WalletCreateRequestFromJSON(json: any): WalletCreateRequest {
    return {
        'action': !exists(json, 'action') ? undefined : json['action'],
    };
}

export function WalletCreateRequestToJSON(value?: WalletCreateRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'action': value.action,
    };
}

/**
* @export
* @enum {string}
*/
export enum WalletCreateRequestActionEnum {
    WalletCreate = 'wallet_create'
}


